# ByteTrack Service Configuration

# Tracking Configuration
tracking:
  track_thresh: 0.5
  track_buffer: 30
  match_thresh: 0.8
  mot20: false
  frame_rate: 30

# Kafka Configuration
kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "bytetrack_service"
  auto_offset_reset: "latest"
  max_poll_records: 1

# Topic Configuration
topics:
  input_pattern: "rtmpose_*"
  output_pattern: "bytetrack_{task_id}"

# Processing Configuration
processing:
  batch_size: 1
  max_concurrent_tasks: 5
  timeout_seconds: 30
  max_tracks_per_task: 50

# Track Management
track_management:
  max_disappeared_frames: 30
  min_track_length: 3
  track_smoothing: true

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 