# YOLOX Service Configuration

# Model Configuration
model:
  weights_path: "models/yolox_x.pth"
  confidence_threshold: 0.5
  nms_threshold: 0.45
  input_size: [640, 640]
  device: "cuda"  # or "cpu"

# Kafka Configuration  
kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "yolox_service"
  auto_offset_reset: "latest"
  max_poll_records: 1

# Topic Configuration
topics:
  input_pattern: "raw_frames_*"
  output_pattern: "yolox_{task_id}"

# Processing Configuration
processing:
  batch_size: 1
  max_concurrent_tasks: 5
  timeout_seconds: 30

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 