# RTMPose Service Configuration

# Model Configuration
model:
  weights_path: "models/rtmpose-m_simcc-aic-coco_pt-aic-coco_420e-256x192.pth"
  config_path: "models/rtmpose-m_8xb256-420e_aic-coco-256x192.py" 
  keypoint_threshold: 0.3
  input_size: [256, 192]
  device: "cuda"  # or "cpu"
  num_keypoints: 17  # COCO format

# Kafka Configuration
kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "rtmpose_service"
  auto_offset_reset: "latest"
  max_poll_records: 1

# Topic Configuration  
topics:
  input_pattern: "yolox_*"
  output_pattern: "rtmpose_{task_id}"

# Processing Configuration
processing:
  batch_size: 1
  max_concurrent_tasks: 5
  timeout_seconds: 30
  max_persons_per_frame: 10

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 